### ISSUE TITLE
Minimum deployment requirement

### ISSUE THREAD

**Issue by Jackson0111** [remirobert/CameraEngine#11]
Hey Remy. I was trying to get the new version into my project, which is developed on minimum iOS 8.0, CameraEngine requires minimum 9.2 to do pod install. Is there a way to fix this?

**Comment by remirobert** [comment]
try quickly, to import the source directly in projects to see.
I will try to downgrade.

**Comment by Jackson0111** [comment]
Hey Remi, I still cannot install cameraEngine through pods, any idea?

**Comment by remirobert** [comment]
Can you show me the error please ?

**Comment by remirobert** [comment]
Fixed with new version 0.9.
**CameraEngine** now support iOS8+

Open the issue again, if you got any issue.

**Comment by Jackson0111** [comment]
I still see this error: 
![screen shot 2016-03-30 at 2 58 15 am](https://cloud.githubusercontent.com/assets/13260808/14134208/590df714-f623-11e5-84b1-210edaf8c3e3.png)

**Comment by remirobert** [comment]
That's strange. Let me check that.

**Comment by Jackson0111** [comment]
if it helps, this is my pod file: pod 'CameraEngine', '~> 0.9' and i did pod update

**Comment by remirobert** [comment]
I tried on a production project the new version. This is the **Podfile** I use : 

```ruby
use_frameworks!

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

pod 'RxSwift', '~> 2.0.0-beta.4'
pod 'RxCocoa', '~> 2.0.0-beta.4'
pod 'RxBlocking', '~> 2.0.0-beta.4'

pod 'Parse'
pod 'DynamicColor'
pod 'CameraEngine', '~> 0.9'

pod 'SnapKit'
pod 'Masonry'

pod 'ParseFacebookUtilsV4'
pod 'FBSDKCoreKit'
```

And I don't have any issue during the installation :tada: :balloon: .
Can you show your full **Podfile** ?

**Comment by Jackson0111** [comment]
![screen shot 2016-03-30 at 3 22 01 am](https://cloud.githubusercontent.com/assets/13260808/14134623/9a55c550-f626-11e5-896c-6f242662735b.png)

**Comment by remirobert** [comment]
Ok thanks to sent me back your **Podfile**
So I had the ```platform :ios, '8.0'``` line in mine.
And it still compile and build without any issues.

Can you try to remove the Pods directory, and then ```pod install --verbose```
And see what's going on.

**Comment by Jackson0111** [comment]
I just did pod repo remove master, pod setup then pod install. everything works fine now thanks a lot!!!

**Comment by Jackson0111** [comment]
I also have another question, as you can see I'm using lots of dependencies. Is that necessarily bad? Should I just use dependencies when it comes to animation and UI design in general, or should I write every code myself? What's your opinion on that?

**Comment by remirobert** [comment]
No of course dependencies are great, it can save you a lot of time depending on what you need.
But you can have some issues, with some dependencies, for example, for a new Swift version or something. So my recon for that, is to choose well the dependencies, and use it if it's very useful.
