### ISSUE TITLE
video short delay at beginning

### ISSUE THREAD

**Issue by zinwalin** [remirobert/CameraEngine#4]
the video captured with CameraEngine has a short delay with black screen but with audio, just for about a second. 

is it ok there? maybe u can reproduce this issue.

thanks a lot.

**Comment by remirobert** [comment]
I will give a look at it.

**Comment by zinwalin** [comment]
at the beginning.

**Comment by zinwalin** [comment]
@remirobert  I have integrated CameraEngine within a single View Controller which supports video and picture capture. the issue happened when I start to capture and then switch to taking-picture mode, so there's a gap which demonstrated in video with black for a short period.

**Comment by remirobert** [comment]
fixed

**Comment by otymartin** [comment]
@remirobert Hey this issue still persists.
Every video i've taken with `CameraEngine` starts with a 0.5 second black screen. Whereas other camera's like `iOS, Snapchat & Instagram` dont have this problem.
